### ISSUE TITLE
Redirect Google Lens to the normal image results is not working

### ISSUE THREAD

**Issue by Neurotoxin001** [fanfare/disablegooglelens#2]
Google Chrome 108.0.5359.99
Disable Google Lens 0.0.4

Redirect is not working when I upload image from my PC from here:
`https://www.google.com/search?q=image&tbm=isch&safe=images`

It's works when I upload it from here (url of previous search):
`https://www.google.com/search?tbs=sbi:AMhZZitDPqezOmOMjR75KcTdAQEZx2lZoC9RkL20_1qlvA_1cWUx2wnvZWLZdEBqZlk8qExwTAjhB_1eKG1OCBbv7tDkEEpojxHns08-6Zjy002q6wMnGI0Ezz82dD1UOM_1sJeJOuS32CW_1buvgUt4_1oqazvphpOGRq6A`

It's also works when I paste url to image, w/o uploading it from my PC. But only if it normal url, like this:
`https://www.simplilearn.com/ice9/free_resources_article_thumb/what_is_image_Processing.jpg`
If it's base64 - redirect is not working too.

**Comment by fanfare** [comment]
when it doesn't redirect, does the screen just turn white? and then it stops?

when that happens, there was some sort of error uploading the image; i need to set something to make the screen not white so it displays the error message.

**Comment by Neurotoxin001** [comment]
No it's just showing default google lens page with image that I search


https://user-images.githubusercontent.com/39812401/206663776-cdf0b22a-3659-4c1f-ae8c-ff1434e41694.mp4

**Comment by fanfare** [comment]
i see, thanks for the video that's very helpful. based on the vid, google lens is being served differently in different languages.. i'll see what i can do to make it work in russian and other languages

**Comment by Neurotoxin001** [comment]
Also I noticed that in `background.js` we have:
`  let response = await fetch(`https://lens.google.com/upload?hl=en&re=df&st=${+ new Date()}&ep=gisbubb`, {`
But on google lens when I upload image, before redirect to google lens with result, I got this url with /v2/ in url:
`https://lens.google.com/v2/upload?hl=ru&re=df&st=1670584539092&cd=CM-DlBc&ep=gisbubb`
I added /v2/ to `background.js` but it's not helped.

**Comment by fanfare** [comment]
i've tried several things but cannot replicate google taking me to the `v2/upload` page... based on the video, it looks like the 'lens' results page is being rendered directly on the `v2/upload` URL first. which if that is the case, and you want to try editing the manifest.json file, i would change the `content_scripts` and `web_accessible_resources` to be this:

  ```
"content_scripts": [
    {
      "js": [ "content-script.js" ],
      "run_at": "document_start",
      "matches": [ "https://lens.google.com/*" ],
      "include_globs": [ "*search*", "*v2/upload*" ],
      "css": [ "style.css" ]
    }  
  ],
  "web_accessible_resources": [
    {
      "resources": [ "web.js" ],
      "matches": [ "https://lens.google.com/*" ],
      "include_globs": [ "*search*", "*v2/upload*" ]
    }
  ]
```

just to see what happens

**Comment by Neurotoxin001** [comment]
Seems like google reverted "v2" for me, today I don't get it when search images, so even old version of disablegooglelens working fine

**Comment by fanfare** [comment]
ok; closing for now, will reopen if they roll out v2 everywhere

**Comment by Neurotoxin001** [comment]
Now I start getting "v3", lol. Method with adding `"*v3/upload*"` in web_accessible_resources and content_scripts is working fine.
