### ISSUE TITLE
[BUG] No longer works (Firefox)

### ISSUE THREAD

**Issue by CurtisDS** [fanfare/disablegooglelens#5]
Leads to white blank screen now.

**Comment by pschannes** [comment]
Having the same issue.

**Comment by andrewz1986** [comment]
+1

**Comment by fanfare** [comment]
thanks for the heads up. googled changed something that totally breaks this extension as it is now.

the `lens.google.com` results' html source previously (up until a few hours ago) contained a URL that could be accessed which would show the results like how it used to be, but this URL has now been removed. im seeing if a workaround might be possible rn
